[project]
name = "parsee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "psycopg>=3.2.12",
    "python-decouple>=3.8",
    "wheel>=0.45.1",
]
